NisporError: Eliminate the duplicate memory copy
Changed the `NisporError::bug` and etc functions to take `String` as
argument, so the we don't do duplicate memory copy like:

    (&format("{}", a)).to_string()

Also changed these functions to crate use only.

Signed-off-by: Gris Ge <fge@redhat.com>